version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: jquisenberry/jqweb003:latest
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8180:80"
    networks:
      - webnet
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"    
networks:
  webnet:

